# Generated by Django 4.2 on 2023-05-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedorName', models.CharField(max_length=200)),
                ('proveedorDescription', models.CharField(blank=True, max_length=200)),
                ('proveedorPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedorImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
