# Generated by Django 4.2.1 on 2023-05-25 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productoModelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='productoTalla',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.MinValueValidator('28'), django.core.validators.MaxValueValidator('47')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
