# Generated by Django 4.2.1 on 2023-05-26 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_productomodelo_producto_productotalla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdenName', models.CharField(max_length=200)),
                ('OrdenDescription', models.CharField(blank=True, max_length=200)),
                ('OrdenPrice', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('productoModelo', models.CharField(blank=True, max_length=200)),
                ('productoTalla', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.MinValueValidator('28'), django.core.validators.MaxValueValidator('47')])),
                ('productoImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
